config/routes.rb
Rails.application.routes.draw do
  root 'registrations#index'
  get "/404" => "errors#not_found"
  get "/500" => "errors#exception"

  mount_devise_token_auth_for 'Staff', at: 'api/v1/auth'

  namespace :api do
    namespace :v1 do
      resources :registrations, path: 'participantes', except: [:edit, :update, :destroy] do
        get 'check_in/palestra/:lecture_id', to: 'registrations#check_in_lecture'
        get 'check_in/curso/:course_id', to: 'registrations#check_in_course'
      end
      resources :lectures, path: 'palestras', only: [:index, :show]
      resources :courses, path: 'cursos', only: [:index, :show]
    end
  end

  scope(path_names: { new: 'novo', edit: 'editar' }) do
    resources :registrations, path: 'participantes', except: [:edit, :show, :update, :destroy] do
    end
  end

  get 'certificados/busca', to: 'registrations#certificates_search', as: 'certificates_search'
  match 'certificados/:hash', to: 'registrations#certificates', via: 'get'
  post 'certificados', to: 'registrations#participant_certificates_search'
  match 'certificados/:hash/satads2018', to: 'registrations#satads_certificate', via: 'get'
  match 'certificados/:hash/curso/:course_hash', to: 'registrations#course_certificate', via: 'get'

  match 'relatorio_professores', to: 'registrations#teachers_report', via: 'get'

  get 'busca', to: 'registrations#registration_courses', as: 'registration_courses'
  post 'inscricao_cursos', to: 'registrations#participant_search'
  post 'add_course_to_participant', to: 'registrations#add_course_to_participant'
  match 'inscricao_satads/:hash', to: 'registrations#satads_confirmation', via: 'get'
  match 'inscricao_curso/:hash', to: 'registrations#courses_confirmation', via: 'get'
  match 'inscricao_cursos', to: 'registrations#registration_courses', via: 'get'
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  has_and_belongs_to_many :registrations
  enum turn: { day: false, night: true }
end

app/controllers/api/v1/lectures_controller.rb
module Api::V1
  class LecturesController < ApplicationController
    before_action :set_lecture, only: [:show]

    def index
      time = (Time.now - 3.hours) # heroku - 3 horas

      @lectures = Lecture.where(day: time.day).order(:id)

      render json: @lectures, status: :ok
    end

    def show
      render json: @lecture, status: :ok
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_lecture
        @lecture = Lecture.find(params[:id])
      end

  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: [:show]

  def index
    @lectures = Lecture.all
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end

end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_form.html.erb
<%= form_with(model: lecture, local: true) do |form| %>
  <% if lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :lecture_name %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration, id: :lecture_duration %>
  </div>

  <div class="field">
    <%= form.label :speaker %>
    <%= form.text_field :speaker, id: :lecture_speaker %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lectures</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Duration</th>
      <th>Speaker</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= lecture.name %></td>
        <td><%= lecture.duration %></td>
        <td><%= lecture.speaker %></td>
        <td><%= link_to 'Show', lecture %></td>
        <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lecture', new_lecture_path %>

app/views/lectures/new.html.erb
<h1>New Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Back', lectures_path %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lecture.name %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @lecture.duration %>
</p>

<p>
  <strong>Speaker:</strong>
  <%= @lecture.speaker %>
</p>

<%= link_to 'Edit', edit_lecture_path(@lecture) %> |
<%= link_to 'Back', lectures_path %>