config/routes.rb
Rails.application.routes.draw do
  root 'registrations#index'
  get "/404" => "errors#not_found"
  get "/500" => "errors#exception"

  mount_devise_token_auth_for 'Staff', at: 'api/v1/auth'

  namespace :api do
    namespace :v1 do
      resources :registrations, path: 'participantes', except: [:edit, :update, :destroy] do
        get 'check_in/palestra/:lecture_id', to: 'registrations#check_in_lecture'
        get 'check_in/curso/:course_id', to: 'registrations#check_in_course'
      end
      resources :lectures, path: 'palestras', only: [:index, :show]
      resources :courses, path: 'cursos', only: [:index, :show]
    end
  end

  scope(path_names: { new: 'novo', edit: 'editar' }) do
    resources :registrations, path: 'participantes', except: [:edit, :show, :update, :destroy] do
    end
  end

  get 'certificados/busca', to: 'registrations#certificates_search', as: 'certificates_search'
  match 'certificados/:hash', to: 'registrations#certificates', via: 'get'
  post 'certificados', to: 'registrations#participant_certificates_search'
  match 'certificados/:hash/satads2018', to: 'registrations#satads_certificate', via: 'get'
  match 'certificados/:hash/curso/:course_hash', to: 'registrations#course_certificate', via: 'get'

  match 'relatorio_professores', to: 'registrations#teachers_report', via: 'get'

  get 'busca', to: 'registrations#registration_courses', as: 'registration_courses'
  post 'inscricao_cursos', to: 'registrations#participant_search'
  post 'add_course_to_participant', to: 'registrations#add_course_to_participant'
  match 'inscricao_satads/:hash', to: 'registrations#satads_confirmation', via: 'get'
  match 'inscricao_curso/:hash', to: 'registrations#courses_confirmation', via: 'get'
  match 'inscricao_cursos', to: 'registrations#registration_courses', via: 'get'
end

app/controllers/api/v1/courses_controller.rb
module Api::V1
  class CoursesController < ApplicationController
    before_action :set_course, only: [:show]

    def index
      @courses = Course.all
      render json: @courses, status: :ok
    end

    def show
      render json: @course, status: :ok
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_course
        @course = Course.find(params[:id])
      end

  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show]

  def index
    @courses = Course.all
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :course_name %>
  </div>

  <div class="field">
    <%= form.label :speaker %>
    <%= form.text_field :speaker, id: :course_speaker %>
  </div>

  <div class="field">
    <%= form.label :vacancies %>
    <%= form.text_field :vacancies, id: :course_vacancies %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration, id: :course_duration %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Speaker</th>
      <th>Vacancies</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.speaker %></td>
        <td><%= course.vacancies %></td>
        <td><%= course.duration %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Speaker:</strong>
  <%= @course.speaker %>
</p>

<p>
  <strong>Vacancies:</strong>
  <%= @course.vacancies %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @course.duration %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>